CREATE TABLE IF NOT EXISTS workflows (
    workflow_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    schedule_type VARCHAR(20) NOT NULL,
    schedule_spec VARCHAR(255) NOT NULL,
    overlap_policy VARCHAR(20) NOT NULL DEFAULT 'SKIP',
    is_paused BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
    job_id VARCHAR(64) PRIMARY KEY,
    workflow_id VARCHAR(64) NOT NULL REFERENCES workflows(workflow_id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    job_class VARCHAR(500) NOT NULL,
    retry_policy VARCHAR(30) NOT NULL DEFAULT 'NONE',
    max_attempts INT NOT NULL DEFAULT 1,
    timeout_seconds INT NOT NULL DEFAULT 300,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_dependencies (
    job_id VARCHAR(64) NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    depends_on_job_id VARCHAR(64) NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, depends_on_job_id),
    CHECK (job_id <> depends_on_job_id)
);

CREATE TABLE IF NOT EXISTS workflow_runs (
    workflow_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id VARCHAR(64) NOT NULL REFERENCES workflows(workflow_id) ON DELETE CASCADE,
    trigger_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    workflow_id VARCHAR(64) NOT NULL REFERENCES workflows(workflow_id) ON DELETE CASCADE,
    workflow_run_id BIGINT NOT NULL,
    attempt_number INT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    duration_ms BIGINT,
    error_message VARCHAR(2000),
    output_summary VARCHAR(2000)
);

CREATE INDEX IF NOT EXISTS idx_job_runs_job_id_started_at ON job_runs (job_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_runs_status ON job_runs (status);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_workflow_id ON workflow_runs (workflow_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_workflow_id ON jobs (workflow_id);
